server:
  port: 9999

spring:
  datasource:
      url: jdbc:mysql://123.57.194.211:3306/tools?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Zhl254827
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
#      active: dev
      active: prod


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #typeAliasesPackage: com.example.huafeng_serve.**.entity
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      #pagination-type: com.baomidou.mybatisplus.extension.plugins.pagination.optimize.JsqlParserCountOptimize